version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.4-node
    steps:
      - checkout

      - setup_remote_docker:
          docker_layer_caching: true

      - run:
          name: Build and push Docker image
          command: |
            docker build -t demikl/kube-fluentd-operator:$CIRCLE_TAG .
            echo $DOCKER_PWD | docker login -u $DOCKER_LOGIN --password-stdin
            docker push demikl/kube-fluentd-operator:$CIRCLE_TAG

workflows:
  version: 2
  build_and_push:
    jobs:
      - build:
          filters:
            tags:
              only: /v[0-9]+(\.[0-9]+)*/
            branches:
              ignore: /.*/